# Generated by Django 4.2 on 2023-04-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_child_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='age',
            field=models.CharField(max_length=50),
        ),
    ]
