# Generated by Django 4.2 on 2023-04-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_activity_alter_roster_time_entered'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='activities',
            field=models.ManyToManyField(to='main_app.activity'),
        ),
    ]
