# Generated by Django 4.2 on 2023-04-22 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_child_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roster',
            options={'ordering': ['-date']},
        ),
    ]
