# Generated by Django 4.2 on 2023-04-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_roster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='note',
            field=models.TextField(default='', max_length=275),
        ),
    ]
