# Generated by Django 4.2 on 2023-04-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_child_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='note',
            field=models.TextField(blank=True, max_length=275),
        ),
    ]
