# Generated by Django 4.2 on 2023-04-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_child_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roster',
            name='checkin_status',
            field=models.BooleanField(),
        ),
    ]
