# Generated by Django 4.2 on 2023-04-19 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_roster_checkin_status_roster_time_entered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('duration', models.CharField(max_length=35)),
            ],
        ),
        migrations.AlterField(
            model_name='roster',
            name='time_entered',
            field=models.TimeField(default=''),
        ),
    ]
